# Branching3 v1b Rule - B3/S2
# Birth on 3 neighbors, Survival on 2 neighbors
# Designed for aggressive branching with lower stability

[metadata]
name = "branching3_v1b"
version = "1.0"
description = "B3/S2 - Aggressive branching with lower survival threshold"
author = "vertex_helper"
date = "2025-01-15"

[rule]
type = "outer-totalistic"
neighborhood = "moore"  # 26 neighbors in 3D
dimension = 3

# Birth conditions: cell becomes alive if exactly 3 neighbors are alive
[rule.birth]
counts = [3]

# Survival conditions: cell stays alive if exactly 2 neighbors are alive
[rule.survival]
counts = [2]

[states]
# Multi-state support (currently using binary: VOID=0, STRUCTURAL=1)
void = 0
structural = 1
compute = 2
energy = 3
sensor = 4

[parameters]
# Default state for new cells
default_state = 0  # VOID

# State for born cells
birth_state = 1  # STRUCTURAL

# Boundary conditions
boundary = "periodic"  # wrap around edges

[metrics]
# Metrics to compute during simulation
track_branching_factor = true
track_connectivity = true
track_survival_rate = true
track_density = true
track_giant_component = true

[notes]
rationale = """
B3/S2 rule designed for aggressive branching growth:
- Birth on 3 neighbors: Lower threshold for spawning new cells
- Survival on 2 neighbors: Stricter survival creates dynamic structures
- Expected behavior: More aggressive branching, higher turnover
- Complexity: Higher (more dynamic, less stable than v1)
"""

expected_behavior = """
- Initial seed expands rapidly
- Forms aggressive branching structures with 3-6 branches per node
- Less stable cores, more dynamic growth
- Higher density (10-25% alive cells)
- More fragmented structures (60-80% giant component)
- Higher branching factor than v1
"""
