# Sample Configuration File with parameters
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
simulation:
  steps: 1000
  agents: 100
