// Type declarations for the WASM module (generated by wasm-pack)
declare module '../pkg/uft_ca.js' {
  export default function init(): Promise<void>
  export class WasmLattice {
    constructor(size: number)
    static from_genome(json_str: string, size: number): WasmLattice
    step(): string
    step_n(n: number): string
    state_buffer(): Uint8Array
    memory_channel(ch: number): Float32Array
    render_data(): Float32Array
    size(): number
    generation(): number
    census(): string
    set_seed(seed: bigint): void
  }
}
