name: Agent Safety Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  agent-safety:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OPA
        run: |
          set -euxo pipefail
          curl -L -o opa https://openpolicyagent.org/downloads/v0.59.0/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/opa
          opa version

      - name: OPA fmt + check
        run: |
          set -euxo pipefail
          mkdir -p dist
          # Show any formatting diffs (does not fail build)
          { opa fmt policy/ --diff || true; } | tee dist/fmt.txt
          # Fail on invalid policy
          opa check policy/

      - name: OPA unit tests (coverage)
        run: |
          set -euxo pipefail
          opa test -v --coverage policy/ | tee dist/coverage.txt
          opa test --coverage --format=json policy/ > dist/opa_coverage.json

      - name: Run matrix (if present)
        run: |
          set -euxo pipefail
          if [ -f scripts/matrix_runner.sh ]; then
            chmod +x scripts/matrix_runner.sh
            ./scripts/matrix_runner.sh | tee dist/matrix_run.txt
          else
            echo "matrix_runner.sh not found; skipping matrix run" | tee dist/matrix_run.txt
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-safety-artifacts
          path: |
            dist/**
