name: docs-deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Build docs
        run: |
          if [ -f docs/package.json ]; then
            cd docs; npm ci || npm i; npm run build || npm run docs || echo "no docs build"; cd -
          elif [ -f mkdocs.yml ]; then
            pip install mkdocs mkdocs-material; mkdocs build
          else
            mkdir -p dist && echo "<h1>No docs build configured</h1>" > dist/index.html
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            dist
            site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4