name: nightly-bench
on:
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benches:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install bench deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-benchmark
      - name: Run benchmarks (non-failing)
        run: |
          pytest -q -k "bench or benchmark" || true
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-results
          path: ./**/.benchmarks/**/*
          if-no-files-found: ignore