
name: "SBOM Generation"

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r testing_requirements.txt
        pip install cyclonedx-bom

    - name: Generate SBOM
      run: |
        cyclonedx-py requirements -r testing_requirements.txt -o sbom.json --format json
        cyclonedx-py requirements -r testing_requirements.txt -o sbom.xml --format xml

    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-${{ github.ref_name }}
        path: |
          sbom.json
          sbom.xml

    - name: Attach SBOM to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          sbom.json
          sbom.xml

    - name: Generate attestation
      if: github.event_name == 'release'
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: |
          sbom.json
          sbom.xml
